const stockProductos = [
    {id:1 ,
    nombre:"Remera Oversize" ,
    precio:300 , 
    categoria:'Remeras', 
    img: 'assets/shirt.jpg' 
    },

    {id:2 ,
    nombre:"Remera Cali" ,
    precio:350 , categoria:'Remeras', 
    img: 'assets/shirt.jpg' },

    {id:3 ,nombre:"Remera Jaspeada" ,precio:200 , categoria:'Remeras', img: 'assets/shirt.jpg' },
    {id:4 ,nombre:"Remera Lisa" ,precio:120 , categoria:'Remeras', img: 'assets/shirt.jpg' },
    {id:5 ,nombre:"Remera ML" ,precio:230 , categoria:'Remeras', img: 'assets/shirt.jpg' },
    {id:6 ,nombre:"Remera MC" ,precio:150 , categoria:'Remeras', img: 'assets/shirt.jpg' },
    {id:7 ,nombre:"Pantalon Luli" ,precio:600 , categoria:'Pantalones', img:'assets/jeans.jpeg' },
    {id:8 ,nombre:"Pantalon Chupin" ,precio:400 , categoria:'Pantalones', img:'assets/jeans.jpeg' },
    {id:9 ,nombre:"Pantalon Chino" ,precio:310 , categoria:'Pantalones', img:'assets/jeans.jpeg' },
    {id:10 ,nombre:"Pantalon Mom" ,precio:700 , categoria:'Pantalones', img:'assets/jeans.jpeg' },
    {id:11 ,nombre:"Pantalon Cargo" ,precio:680 , categoria:'Pantalones', img:'assets/jeans.jpeg' },
    {id:12 ,nombre:"Camisa Cuadros" ,precio:500 , categoria:'Camisas', img: 'assets/camisa.jpeg' },
    {id:13 ,nombre:"Camisa Rayas" ,precio:320 , categoria:'Camisas', img: 'assets/camisa.jpeg' },
    {id:14 ,nombre:"Camisa Jean" ,precio:1000 , categoria:'Camisas', img: 'assets/camisa.jpeg' },
    {id:15 ,nombre:"Camisa Mao" ,precio:800 , categoria:'Camisas', img: 'assets/camisa.jpeg' },
    {id:16 ,nombre:"Camisa Lino" ,precio:700 , categoria:'Camisas', img: 'assets/camisa.jpeg' },
    {id:17 ,nombre:"Campera Liviana" ,precio:770 , categoria:'Camperas',img:'assets/campera.jpg' },
    {id:18 ,nombre:"Campera Gui" ,precio:635 , categoria:'Camperas',img:'assets/campera.jpg' },
    {id:19 ,nombre:"Zapatillas Clasicas" ,precio:1200 , categoria:'Zapatillas', img: 'assets/sneakers.jpeg' },
    {id:20 ,nombre:"Zapatillas Deportivas" ,precio:1100, categoria:'Zapatillas', img: 'assets/sneakers.jpeg' },
    {id:21 ,nombre:"Zapatos de Vestir" ,precio:1050, categoria:'Zapatillas', img: 'assets/sneakers.jpeg' },
    {id:22 ,nombre:"Campera Puff" ,precio:2000, categoria:'Camperas',img:'assets/campera.jpg' },
    {id:23 ,nombre:"Gorra MUI" ,precio:250, categoria:'Accesorios', img: 'assets/hat.jpg' },
    {id:24 ,nombre:"Accesorio Gorra CL" ,precio:180 , categoria:'Accesorios',img: 'assets/hat.jpg' }
];